runtime: python
env: flex
entrypoint: gunicorn -b :$PORT testpf.wsgi

runtime_config:
  python_version: 3

beta_settings:
    cloud_sql_instances: citric-sprite-220706:us-central1:pftest

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
     SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:root@/posdb?unix_socket=/cloudsql/citric-sprite-220706:us-central1:pftest

# runtime: python
#
# # the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
# # entrypoint: gunicorn -b :$PORT PROJECT-DIRECTORY.wsgi # specific to a GUnicorn HTTP server deployment
# env: flex # for Google Cloud Flexible App Engine
#
# # any environment variables you want to pass to your application.
# # accessible through os.environ['VARIABLE_NAME']
# env_variables:
# # the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
#   SECRET_KEY: 'rc=^m)&jx)02&dp-6r1&99e@2rq7$sd1a3e^2twan-(e92l#=h'
#   DEBUG: 'False' # always False for deployment
#
# # everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# # the DATABASE-NAME is the name you gave your project's PostgreSQL database
# # the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
#   DB_HOST: '/cloudsql/trim-icon-205507:asia-east1:lgmsdatabase'
#   DB_PORT: '5432' # PostgreSQL port
#   DB_NAME: 'lgmsdatabase'
#   DB_USER: 'postgres' # either 'postgres' (default) or one you created on the PostgreSQL instance page
#   DB_PASSWORD: 'postgres'
#
#   STATIC_URL: 'https://storage.googleapis.com/trim-icon-205507/static/' # this is the url that you sync static files to
#
# handlers:
# - url: /static
#   static_dir: static
#
# beta_settings:
# # from command >> gcloud sql instances describe DATABASE-NAME <<
#   cloud_sql_instances: trim-icon-205507:asia-east1:lgmsdatabase
#   #trim-icon-205507:asia-east1:lgmsdatabase
#
# runtime_config:
#   python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4
